jdbc.driverClassName=org.postgresql.Driver
jdbc.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
jdbc.username=${POSTGRES_USER}
jdbc.password=${POSTGRES_PASSWORD}

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.hbm2ddl.import_files_sql_extractor=org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

#none,create,drop,drop-and-create
javax.persistence.schema-generation.database.action=creat
javax.persistence.schema-generation.create-script-source=schema.sql

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder = TRACE